Typo in tardir.R: creative -> create
pik-piam/gms pull request #13
Opened 2022-04-14 10:52 UTC by mikapfl

I love creativity, but not in my tar-producing functions.

2022-04-14 11:40 UTC, mikapfl commented
Hm, lucode2-check wasn't finished after 38 minutes, 35 of which it was trying to run the actual tests. I cancelled and re-started the run, hopefully this one is more successful.

2022-04-19 13:11 UTC, mikapfl commented
I re-started the lucode2-check CI job, hopefully third time's the charm.

2022-04-22 09:45 UTC, tscheypidi requested changes
just one suggestion to shorten a bit the code fix

2022-04-22 09:45 UTC, tscheypidi commented on R/singleGAMSfile.R
> +      if (!is.null(remainder)) {
The `if`-statement is not necessary and you can just add the `remainder` in the line above independent of whether it is NULL or not. ( `c(1,2) == c(1,2,NULL)`)

2022-04-22 09:48 UTC, mikapfl commented on R/singleGAMSfile.R
> +      if (!is.null(remainder)) {
strange, I thought I tried that and it didn't work. But probably I was confused, because I first tried with an empty list or an empty vector, and those didn't work as I thought. Thanks for spotting it!

2022-04-22 10:03 UTC, tscheypidi approved these changes

2022-04-22 10:14 UTC, merged