singleGAMSfile: add option to also embed executed R scripts
pik-piam/gms pull request #15
Opened 2022-04-27 15:22 UTC by mikapfl

Hi,

This adds an option to singleGAMSfile to als embed R scripts which are executed using
```gams
Execute "Rscript path/to/script.R";
```
in GAMS. This will be transformed into
```gams
$onecho > script.R
<content of script.R>
$offecho
Execute "Rscript script.R";
```

The transformation is not enabled by default but gated behind a boolean flag argument so that users can choose themselves to enable the transformation.

Cheers,

Mika

2022-04-27 15:57 UTC, tscheypidi requested changes
looks good, only the filename of the resulting R scripts needs to be a bit more name collision proof

2022-04-27 15:57 UTC, tscheypidi commented on R/singleGAMSfile.R
> +        baseRFileName <- basename(rFileName)
using only the basename I see some risk of name collisions. Perhaps use the whole path instead and replace / with _ or use a hash to get a unique file name?

2022-04-27 16:15 UTC, mikapfl commented on R/singleGAMSfile.R
> +        baseRFileName <- basename(rFileName)
I think using a hash is pretty bad because it obscures the source of code. The whole path altered to not require creation of directories sounds good, will do.

2022-04-27 16:22 UTC, mikapfl commented on R/singleGAMSfile.R
> +        baseRFileName <- basename(rFileName)
Done

2022-04-28 07:20 UTC, tscheypidi approved these changes
I think you can simplify the gsub statement (see my suggestion). Other than that it looks good.

2022-04-28 07:20 UTC, tscheypidi commented on R/singleGAMSfile.R
> +        newRFileName <- gsub("\\", "_", gsub("/", "_", rFileName, fixed = TRUE), fixed = TRUE)
```suggestion
        newRFileName <- gsub("[\\/]", "_", rFileName)
```

2022-04-28 09:37 UTC, merged