add chooseFromList with various options
pik-piam/gms pull request #32
Opened 2022-08-08 14:20 UTC by orichters

As discussed with @tscheypidi, a new generic function `chooseFromList` is added.

It is a cleaned version of the one I wrote in REMIND's [`start.R`](https://github.com/remindmodel/remind/blob/develop/start.R#L53-L133), based on various special versions such as `chooseFolder` that have been there for a while by different authors.

Features:
- works with character vectors and lists, and returns the same type
- `multiple` allows to select more than one 
- selection can be based on picking individual or multiple entries, including 2:5 which implies 2,3,4,5, `all` or regex matching
- the selected entries can be returned as a list, or as a boolean list with the same size as the original one
- supports selection based on groups supplied as vector/list names

@mikapfl: It would be great if you could check the lucode2::buildLibrary() changes and the tests.

2022-08-08 15:26 UTC, mikapfl requested changes
Looks good to me! In particular, the tests inspire confidence that at least the happy path works well.

The function is quite long and therefore at times hard to follow. Maybe it would be worth to try to split it into three or four functions (in the same file), all called by the main function in order? Like `printOptions()`, `parseRawInput()`, `parseRegex()` or so? Would certainly help whoever has to come back to this in 3-4 years. But I'd be also fine with merging as-is if you don't have the time for refactoring.

2022-08-08 15:26 UTC, mikapfl commented on R/chooseFromList.R
> +#' @param group list with same dimension as theList with group names to allow to select whole groups
```suggestion
#' @param group list with same dimension as theList with group names to allow to select whole groups, optional
```

2022-08-08 15:26 UTC, mikapfl commented on R/chooseFromList.R
> +  }
I think it is better to be specific with the error message, so make two `ifs`. Also, group with a different dimension than theList is simply an error, not something I would try to recover.

2022-08-08 15:26 UTC, mikapfl commented on R/chooseFromList.R
> +  if (! isFALSE(group)) {
just double-checking: `! isFALSE(group)` is not the same as `isTRUE(group)` or `boolean(group)` or some other formulation which is saner?

2022-08-08 15:26 UTC, mikapfl commented on R/chooseFromList.R
> +  }
this could well be extracted into its own (private) function in the same file. Then it could also be tested with one or two quick tests. (optional, if you like to do some refactoring to get the cyclomatic complexity of the function down)

2022-08-08 15:34 UTC, orichters commented
I don't understand why the checks fail: https://github.com/pik-piam/gms/runs/7728861581?check_suite_focus=true
It does not happen while running the checks on the cluster, seems to be related to [some R mode change](https://stackoverflow.com/questions/72848442/r-warning-lengthx-2-1-in-coercion-to-logical1) and I'm unable to debug it. Maybe @mikapfl you have an idea?

2022-08-08 15:35 UTC, orichters commented on R/chooseFromList.R
> +  if (! isFALSE(group)) {
no, because if `group <- c("A", "B")`, then `isTRUE(group)` is FALSE. I want `TRUE` only if `group` is indeed `FALSE`, nothing else.

2022-08-08 15:43 UTC, mikapfl commented
> I don't understand why the checks fail: https://github.com/pik-piam/gms/runs/7728861581?check_suite_focus=true It does not happen while running the checks on the cluster, seems to be related to [some R mode change](https://stackoverflow.com/questions/72848442/r-warning-lengthx-2-1-in-coercion-to-logical1) and I'm unable to debug it. Maybe @mikapfl you have an idea?

I get these errors also when testing on my laptop with R 4.2, I guess you don't get them on the cluster because there we have R 4.1.

I don't know immediately what is happening there and why it is unhappy.

2022-08-08 15:49 UTC, mikapfl commented
I guess it would be easier to debug if R could tell me at which line the coercion to logical doesn't work. I'll never get used to these utterly incomplete tracebacks from R.

2022-08-08 15:56 UTC, mikapfl commented on R/chooseFromList.R
> +  if (multiple && length(identifier == 1) && identifier == length(theList)) {
here, `identifier` can be a list with more than one entry. therefore `identifier == length(theList)` can also be a list with mor than one entry. Coercing it to boolean will then raise a warning.

2022-08-08 15:57 UTC, mikapfl commented on R/chooseFromList.R
> +  if (multiple && length(identifier == 1) && identifier == length(theList)) {
```suggestion
  if (multiple && length(identifier) == 1 && identifier == length(theList)) {
```
Is probably more correct?

2022-08-08 15:57 UTC, orichters commented
> I guess it would be easier to debug if R could tell me at which line the coercion to logical doesn't work. I'll never get used to these utterly incomplete tracebacks from R.

Yeah, terrible! But there are only two `length(...) > 1` statements, [here](https://github.com/pik-piam/gms/pull/32/files#diff-228cc631ecba462ee423b90b5a3a4b6d59fe2b3d309c7dfde8f34781a88c7d73R60) and [here](https://github.com/pik-piam/gms/pull/32/files#diff-228cc631ecba462ee423b90b5a3a4b6d59fe2b3d309c7dfde8f34781a88c7d73R68), but I already added the `isTRUE` such that it coerces to a unique result. Maybe `all()` instead?

2022-08-08 15:59 UTC, orichters commented on R/chooseFromList.R
> +  if (multiple && length(identifier == 1) && identifier == length(theList)) {
Baaah, Must be `length(identifier) == 1` of course :(

2022-08-08 15:59 UTC, mikapfl commented on R/chooseFromList.R
> +  if (multiple && length(identifier == 1) && identifier == length(theList)) {
I got to the right line with `options(warn=2, error=recover)` - seems to be the go-to debugging tool for when you need to know where the warning actually happened.

2022-08-08 16:06 UTC, chroetz commented on R/chooseFromList.R
> +  identifier <- tmp
Just a note: This is a short version for parsing the user input: `eval(parse(text = paste("c(", input, ")")))`.
It puts the input into `c()` and evaluates it as an R expression.

2022-08-08 16:14 UTC, chroetz commented
Thanks for doing this, @orichters! It also bothered me for some time that there a several duplications of functions like this in different scripts in the REMIND repo. I even added my [own](https://github.com/remindmodel/remind/blob/050cf6fa622ee8eab3f7dd51f8d1e042764d0d42/scripts/output/comparison/compareScenarios2.R#L31)... In that implementation, there are default choices which are selected if the user just hits enter. Furthermore, the default choices are colored with `crayon`. What do you think about adding this feature to `gms::chooseFromList()`?

2022-08-08 16:25 UTC, orichters commented on R/chooseFromList.R
> +  }
done

2022-08-08 16:25 UTC, orichters commented on R/chooseFromList.R
> +#' @param group list with same dimension as theList with group names to allow to select whole groups
done

2022-08-09 07:26 UTC, orichters commented on R/chooseFromList.R
> +  identifier <- tmp
I'm not that sure this is a good idea, at least without extensive checks for the input the user provides. This is at least what I learned from [Little Bobby Tables](https://xkcd.com/327/).

2022-08-09 07:35 UTC, mikapfl commented on R/chooseFromList.R
> +  identifier <- tmp
The user is running arbitrary code already. There is no security boundary here. If the user wants to crash the program, they can just hit `ctrl+c`. So feel free to `eval` whatever the user hands to you if it makes your code cleaner.

The problem I see with `eval`'ing here is more about error messages. If the user inputs "`list(1,2,3)`", that could lead to absolutely hilarious error messages down the line. Here, it is much more helpful to tell the user early that "you must input a number".

2022-08-09 07:53 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q requested changes

2022-08-09 07:53 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented on R/chooseFromList.R
> +#'
This function needs examples.

2022-08-09 07:53 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented on R/chooseFromList.R
> +              " Group"))
You are missing a new line here, `Group` gets conflated with `1: all` in the output:
```
> chooseFromList(theList = list('one', 'two', 'three'), group = c('one' = 'odd', 'two' = 'even', 'three' = 'odd'))


Please choose runs:

          Group1: all
2: one    odd
3: two    even
4: three  odd
5: Group: even
6: Group: odd
7: Search by pattern...
Numbers entered as 2,4:6,9 (runs): 
```

2022-08-09 07:53 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented on R/chooseFromList.R
> +#' @param group list with same dimension as theList with group names to allow to select whole groups, optional
You call it a "list", but the function breaks when an actual `list` is supplied:
```
> chooseFromList(theList = list('one', 'two', 'three'), group = list('one' = 'odd', 'two' = 'even', 'three' = 'odd'))
Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) : 
  'x' must be atomic
```
Either fix the code, or call it a (character) vector.

2022-08-09 07:53 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented on R/chooseFromList.R
> +#' @param group list with same dimension as theList with group names to allow to select whole groups, optional
Why are `theList` and `group` separate parameters?  Users have to repeat the same data, once as data proper (`theList`), once as names to a named vector.  Quite cumbersome.
Why not use just one input, with list items to choose as data and optional groups as names?

2022-08-09 07:53 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented on R/chooseFromList.R
> +#' @param allowEmpty TRUE: allows you not to select anything (returns NA). FALSE: must select something
Users should always have an explicit option to choose nothing and abort.  Else they just hit CTRL-C.
If there's too much legacy code that can't handle the user choosing nothing, this could be changed to a parameter that quits the R script if the user chooses nothing, instead of returning control (probably the most common use case for us).

2022-08-09 07:53 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented on R/chooseFromList.R
> +#' @param userinput string provided by the user. If not supplied, user is asked
Out of curiosity: what is the use case for this?

2022-08-09 08:09 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented
Also, have you given thought to improving list presentation?  The [list in `choose_slurmConfig.R`](https://github.com/remindmodel/remind/blob/050cf6fa622ee8eab3f7dd51f8d1e042764d0d42/scripts/start/choose_slurmConfig.R#L16-L35) has usability features (section delimiters) that could improve lots of other use cases.  They could be implemented as a special case/escape sequence like treating all items starting with five dashes as separators
```
> modes <- c("SLURM standby               12   nash H12             [recommended]",
           "SLURM standby               13   nash H12 coupled",
           "SLURM standby               16   nash H12+",
           "SLURM standby                1   nash debug, testOneRegi, quick",
           "-----",
           "SLURM priority              12   nash H12             [recommended]",
           "SLURM priority              13   nash H12 coupled",
           "SLURM priority              16   nash H12+", 
           "SLURM priority               1   nash debug, testOneRegi, quick", 
           "-----",
           "SLURM short                 12   nash H12",
           "SLURM short                 16   nash H12+", 
           "SLURM short                  1   nash debug, testOneRegi, quick", 
           "SLURM medium                 1   negishi",
           "SLURM long                   1   negishi", 
           "-----",
           "SLURM medium                12   nash - long calibration", 
           "SLURM medium                16   nash - long calibration",
           "-----", 
           "direct, without SLURM")
> chooseFromList(modes, multiple = FALSE)


Please choose runs:

 1: SLURM standby               12   nash H12             [recommended]
 2: SLURM standby               13   nash H12 coupled
 3: SLURM standby               16   nash H12+
 4: SLURM standby                1   nash debug, testOneRegi, quick
    -------------------------------------------------------------------
 5: SLURM priority              12   nash H12             [recommended]
 6: SLURM priority              13   nash H12 coupled
 7: SLURM priority              16   nash H12+
 8: SLURM priority               1   nash debug, testOneRegi, quick
    -------------------------------------------------------------------
 9: SLURM short                 12   nash H12
10: SLURM short                 16   nash H12+
11: SLURM short                  1   nash debug, testOneRegi, quick
12: SLURM medium                 1   negishi
13: SLURM long                   1   negishi
    -------------------------------------------------------------------
14: SLURM medium                12   nash - long calibration
15: SLURM medium                16   nash - long calibration
    -------------------------------------------------------------------
16: direct, without SLURM
Number (runs):
```
Maybe for future improvement `;)`

2022-08-09 08:13 UTC, orichters commented on R/chooseFromList.R
> +#' @param group list with same dimension as theList with group names to allow to select whole groups, optional
`group` is optional, see last word in the param description. I like your idea though to merge it into one list…

2022-08-09 08:17 UTC, orichters commented on R/chooseFromList.R
> +#' @param userinput string provided by the user. If not supplied, user is asked
Main reason: for `testthat` for [the function tests](https://github.com/pik-piam/gms/pull/32/files#diff-5b23d4fd60a302196db0d52c010ef6dfac47ef663a0ab602ba8007bf8c594600), because there seems to be no easy solution to deal with the `getLine()` calls, and I agreed with @mikapfl that this is a good option.

Minor reason: If at some point somebody want to migrate `choose_slurmConfig()` to this option, it allows to specify the identifier aka userinput as input from a scenario config file.

2022-08-09 10:26 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented on R/chooseFromList.R
> +#' @param group list with same dimension as theList with group names to allow to select whole groups, optional
That's why I suggested group names to be optional, see third to last word in my suggestion.

2022-08-09 10:31 UTC, orichters commented on R/chooseFromList.R
> +#' @param group list with same dimension as theList with group names to allow to select whole groups, optional
I think this is a misunderstanding. You essentially had `theList <- c(1, 2, "A")` and you optionally `group <- c("Num", "Num", "Letter")`. But I prefer it with `theList <- c(Num = 1, Num = 2, Letter = "A")` as you suggested.

2022-08-09 13:28 UTC, orichters commented on R/chooseFromList.R
> +#' @param allowEmpty TRUE: allows you not to select anything (returns NA). FALSE: must select something
Ok. I deleted the `allowEmpty` option. An empty list or character vector is then returned.

2022-08-09 13:28 UTC, orichters commented on R/chooseFromList.R
> +#' @param group list with same dimension as theList with group names to allow to select whole groups, optional
I implemented the `group` feature as list / character vector names.

2022-08-09 13:32 UTC, orichters commented on R/chooseFromList.R
> +#' @param group list with same dimension as theList with group names to allow to select whole groups, optional
The problem was that you did not understand the `group` feature as I implemented it. But as I re-implemented it, this should be fine. `chooseFromList(theList = list("odd" = 1, "even" = "two", "odd" = "three"))` works.

2022-08-09 13:32 UTC, orichters commented on R/chooseFromList.R
> +#'
done

2022-08-09 13:34 UTC, orichters commented
> Thanks for doing this, @orichters! It also bothered me for some time that there a several duplications of functions like this in different scripts in the REMIND repo. I even added my [own](https://github.com/remindmodel/remind/blob/050cf6fa622ee8eab3f7dd51f8d1e042764d0d42/scripts/output/comparison/compareScenarios2.R#L31)... In that implementation, there are default choices which are selected if the user just hits enter. Furthermore, the default choices are colored with `crayon`. What do you think about adding this feature to `gms::chooseFromList()`?

I added the option to specify a group named `default` which is selected if the user types nothing. I tried a bit with coloring, but the characters added by the crayon function messes with the layout of the groups, so people have to live without colors.

2022-08-09 13:35 UTC, orichters commented on R/chooseFromList.R
> +  }
I used the quicker version by @chroetz and put the pattern matching into a single function, so R is not annoyed about cyclomatic complexity anymore.

2022-08-09 13:44 UTC, mikapfl approved these changes

2022-08-09 14:39 UTC, orichters commented
> Also, have you given thought to improving list presentation? The [list in `choose_slurmConfig.R`](https://github.com/remindmodel/remind/blob/050cf6fa622ee8eab3f7dd51f8d1e042764d0d42/scripts/start/choose_slurmConfig.R#L16-L35) has usability features (section delimiters) that could improve lots of other use cases. They could be implemented as a special case/escape sequence like treating all items starting with five dashes as separators. Maybe for future improvement `;)`

The other necessity before slurmConfig can be chosen based on this function would be to implement that the options presented to the user are different to what is actually selected…

2022-08-09 14:58 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented
> The other necessity before slurmConfig can be chosen based on this function would be to implement that the options presented to the user are different to what is actually selected…

I don't follow.  How so?

2022-08-09 15:00 UTC, orichters commented
> > The other necessity before slurmConfig can be chosen based on this function would be to implement that the options presented to the user are different to what is actually selected…
> 
> I don't follow. How so?

The users gets to select based on
```
 1: SLURM standby               12   nash H12             [recommended]
...
```
but the actual selection the function returns is
```
--qos=standby --nodes=1 --tasks-per-node=12
...
```
`chooseFromList` does not (yet) allow this.

2022-08-09 15:29 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented
> The users gets to select based on
> 
> ```
>  1: SLURM standby               12   nash H12             [recommended]
> ...
> ```
> 
> but the actual selection the function returns is
> 
> ```
> --qos=standby --nodes=1 --tasks-per-node=12
> ...
> ```
> 
> `chooseFromList` does not (yet) allow this.

No business of `chooseFromList()`.  Simply pass
```
which(chooseFromList(..., returnBoolean = TRUE))
```
into the [following `switch()` statement](https://github.com/remindmodel/remind/blob/050cf6fa622ee8eab3f7dd51f8d1e042764d0d42/scripts/start/choose_slurmConfig.R#L50-L66).

2022-08-10 08:47 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q approved these changes

2022-08-10 09:42 UTC, orichters commented on R/chooseFromList.R
> +  identifier <- tmp
I used two checks now: It checks whether the whole user-input consists of `[0-9,:]` and whether the `eval` produces an error. That should catch the most quirky user input.

2022-08-10 10:10 UTC, merged