Make file distribution optional and better error message
pik-piam/gms pull request #72
Opened 2023-09-26 08:04 UTC by robinhasse

- introduce argument to switch off file distribution in `download_distribute`
  - This allows to use the function also when no distribution is wanted (like in BRICK, potentially EDGE-T).
  - I acknowledge that the function then does little more than `download_unpack` (only changing wd to modelfolder and allow for additional file deletion).
  - If you think this is unnecessary and makes the function name less indicative I can live with removing this change again.
- indicative error message if `files` files are missing
  - I consider this generally useful independent of the above

2023-09-26 08:35 UTC, orichters commented
Wouldn't the alternative simply be to [return `NULL` here in `[getfiledestinations()`](https://github.com/pik-piam/gms/pull/72/files#diff-cbca67827c427537222448ca2f7cd8cb46df5d55fb22792ae0a2d138835dd5c8R20) and then make the distribution conditional on `! is.null(file2destination)`? So if you don't find `input` files, don't distribute anything?

2023-09-26 08:42 UTC, robinhasse commented
> Wouldn't the alternative simply be to [return `NULL` here in `getfiledestinations()`](https://github.com/pik-piam/gms/pull/72/files#diff-cbca67827c427537222448ca2f7cd8cb46df5d55fb22792ae0a2d138835dd5c8R20) and then make the distribution conditional on `! is.null(file2destination)`? So if you don't find `input` files, don't distribute anything?

Thats definitely smarter but changes the default behaviour (though only in case of a former error). I could add a warning that can be suppressed if you don't expect distribution.

2023-09-26 08:51 UTC, orichters commented
I even think a `message` would be sufficient. If you would like to use the function as such in your model, then it shouldn't raise a warning.

2023-09-26 09:49 UTC, robinhasse commented
> I even think a `message` would be sufficient. If you would like to use the function as such in your model, then it shouldn't raise a warning.

I eventually did it the way you suggested. Thanks Oli!

2023-09-26 09:54 UTC, orichters commented on R/download_distribute.R
> +  message("Delete old data in input folders ... ")
That is a bit confusing to get the info that files are deleted when that does not happen. I would prefer:
```
file2destination <- getfiledestinations()
if (is.null(file2destination)) {
  message("No 'input' files found, no data deleted.")
} else {
  message("Delete old data in input folders...")
  delete_olddata(file2destination)
  if (! is.null(additionalDelete)) delete_olddata(additionalDelete)
  message("done!\n")
}
```
or something like that

2023-09-26 10:31 UTC, tscheypidi requested changes
I like the idea of the PR, it just needs some more finetuning (see my specific comments)

2023-09-26 10:31 UTC, tscheypidi commented on R/download_distribute.R
> +    low_res  <- get_info("input/info.txt","^\\* Output ?resolution:",": ")
This functionality and the following lines are not really linked to file2destination. Why are they getting deactivated as well if that file is missing?

2023-09-26 12:42 UTC, robinhasse commented on R/download_distribute.R
> +  message("Delete old data in input folders ... ")
Good point, though the above would allow additionalDelete in cases where you don't distribute. But I'll find a fix.

2023-09-26 12:47 UTC, robinhasse commented on R/download_distribute.R
> +    low_res  <- get_info("input/info.txt","^\\* Output ?resolution:",": ")
I thought it was. If you don't distribute (=> don't call `copy_input`) then what do you need the lines 80-105 for?

2023-09-26 12:55 UTC, robinhasse commented on R/download_distribute.R
> +  message("Delete old data in input folders ... ")
This is for those that cannot have enough messages. I guess there was a reason people wanted this in the log...

2023-09-26 14:05 UTC, orichters approved these changes
Fine from my side, but please wait for Jan's approval…

Please update the PR description such that it fits to what you actually did after the changes.

2023-09-27 21:58 UTC, tscheypidi commented on R/download_distribute.R
> +    low_res  <- get_info("input/info.txt","^\\* Output ?resolution:",": ")
ah, you are right....I got confused by the low_res detection and did not realize that this was only input to the copy command. Sorry!

2023-09-27 22:01 UTC, tscheypidi commented
I made two comments, but was now also not able to see my second one. I was adding to Olivers comment with the messaging the suggestion not to trigger a message at all if not files are to be deleted, as this might be confusing to users not familiar with the function and is probably not necessary to be mentioned. Other than that I think I did not had any further comments

2023-09-27 22:01 UTC, tscheypidi approved these changes

2023-09-28 04:55 UTC, merged